services:
  caddy:
    build: ./caddy
    container_name: rdoc-webrtc-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CF_API_KEY=your CF API Key
      - CF_API_EMAIL=your Email

  mediamtx-jazzz:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: mediamtx-jazzz
    restart: unless-stopped
    ports:
      - "8891:8891/udp"   # SRT
      - "9991:9991/tcp"   # API
      - "8181:8181/udp"   # WebRTC ICE/Media
    environment:
      - MTX_SRT=yes
      - MTX_SRTADDRESS=:8891
      - MTX_API=yes
      - MTX_APIADDRESS=:9991
      - MTX_RTSP=yes
      - MTX_RTSPADDRESS=:8554
      - MTX_RTMP=no
      - MTX_HLS=no
      - MTX_WEBRTC=yes
      - MTX_WEBRTCADDRESS=:8889
      - MTX_WEBRTCLOCALUDPADDRESS=:8181
      - MTX_WEBRTCADDITIONALHOSTS=85.215.253.135
      - MTX_PATHS_JAZZZ_GAME_SOURCE=publisher
      - MTX_PATHS_JAZZZ_GAME_RUNONREADY=ffmpeg -hide_banner -loglevel warning -fflags +genpts -rtsp_transport tcp -i rtsp://127.0.0.1:8554/jazzz_game -c:v copy -af aresample=async=1000:first_pts=0,asetpts=N/SR/TB -c:a libopus -b:a 128k -ar 48000 -ac 2 -max_interleave_delta 0 -muxdelay 0 -muxpreload 0 -f rtsp -rtsp_transport tcp -pkt_size 1200 rtsp://127.0.0.1:8554/jazzz_game_webrtc
      - MTX_PATHS_JAZZZ_GAME_RUNONREADYRESTART=yes
      - MTX_PATHS_JAZZZ_GAME_WEBRTC_SOURCE=publisher

  mediamtx-headwig:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: mediamtx-headwig
    restart: unless-stopped
    ports:
      - "8892:8892/udp"   # SRT
      - "9992:9992/tcp"   # API
      - "8182:8182/udp"   # WebRTC ICE/Media
    environment:
      - MTX_SRT=yes
      - MTX_SRTADDRESS=:8892
      - MTX_API=yes
      - MTX_APIADDRESS=:9992
      - MTX_RTSP=yes
      - MTX_RTSPADDRESS=:8554
      - MTX_RTMP=no
      - MTX_HLS=no
      - MTX_WEBRTC=yes
      - MTX_WEBRTCADDRESS=:8889
      - MTX_WEBRTCLOCALUDPADDRESS=:8182
      - MTX_WEBRTCADDITIONALHOSTS=85.215.253.135
      - MTX_PATHS_HEADWIG_GAME_SOURCE=publisher
      - MTX_PATHS_HEADWIG_GAME_RUNONREADY=ffmpeg -hide_banner -loglevel warning -fflags +genpts -rtsp_transport tcp -i rtsp://127.0.0.1:8554/headwig_game -c:v copy -af aresample=async=1000:first_pts=0,asetpts=N/SR/TB -c:a libopus -b:a 128k -ar 48000 -ac 2 -max_interleave_delta 0 -muxdelay 0 -muxpreload 0 -f rtsp -rtsp_transport tcp -pkt_size 1200 rtsp://127.0.0.1:8554/headwig_game_webrtc
      - MTX_PATHS_HEADWIG_GAME_RUNONREADYRESTART=yes
      - MTX_PATHS_HEADWIG_GAME_WEBRTC_SOURCE=publisher

  mediamtx-jericho:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: mediamtx-jericho
    restart: unless-stopped
    ports:
      - "8893:8893/udp"   # SRT
      - "9993:9993/tcp"   # API
      - "8183:8183/udp"   # WebRTC ICE/Media
    environment:
      - MTX_SRT=yes
      - MTX_SRTADDRESS=:8893
      - MTX_API=yes
      - MTX_APIADDRESS=:9993
      - MTX_RTSP=yes
      - MTX_RTSPADDRESS=:8554
      - MTX_RTMP=no
      - MTX_HLS=no
      - MTX_WEBRTC=yes
      - MTX_WEBRTCADDRESS=:8889
      - MTX_WEBRTCLOCALUDPADDRESS=:8183
      - MTX_WEBRTCADDITIONALHOSTS=85.215.253.135
      - MTX_PATHS_JERICHO_GAME_SOURCE=publisher
      - MTX_PATHS_JERICHO_GAME_RUNONREADY=ffmpeg -hide_banner -loglevel warning -fflags +genpts -rtsp_transport tcp -i rtsp://127.0.0.1:8554/jericho_game -c:v copy -af aresample=async=1000:first_pts=0,asetpts=N/SR/TB -c:a libopus -b:a 128k -ar 48000 -ac 2 -max_interleave_delta 0 -muxdelay 0 -muxpreload 0 -f rtsp -rtsp_transport tcp -pkt_size 1200 rtsp://127.0.0.1:8554/jericho_game_webrtc
      - MTX_PATHS_JERICHO_GAME_RUNONREADYRESTART=yes
      - MTX_PATHS_JERICHO_GAME_WEBRTC_SOURCE=publisher

  mediamtx-polder:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: mediamtx-polder
    restart: unless-stopped
    ports:
      - "8894:8894/udp"   # SRT
      - "9994:9994/tcp"   # API
      - "8184:8184/udp"   # WebRTC ICE/Media
    environment:
      - MTX_SRT=yes
      - MTX_SRTADDRESS=:8894
      - MTX_API=yes
      - MTX_APIADDRESS=:9994
      - MTX_RTSP=yes
      - MTX_RTSPADDRESS=:8554
      - MTX_RTMP=no
      - MTX_HLS=no
      - MTX_WEBRTC=yes
      - MTX_WEBRTCADDRESS=:8889
      - MTX_WEBRTCLOCALUDPADDRESS=:8184
      - MTX_WEBRTCADDITIONALHOSTS=85.215.253.135
      - MTX_PATHS_POLDER_GAME_SOURCE=publisher
      - MTX_PATHS_POLDER_GAME_RUNONREADY=ffmpeg -hide_banner -loglevel warning -fflags +genpts -rtsp_transport tcp -i rtsp://127.0.0.1:8554/polder_game -c:v copy -af aresample=async=1000:first_pts=0,asetpts=N/SR/TB -c:a libopus -b:a 128k -ar 48000 -ac 2 -max_interleave_delta 0 -muxdelay 0 -muxpreload 0 -f rtsp -rtsp_transport tcp -pkt_size 1200 rtsp://127.0.0.1:8554/polder_game_webrtc
      - MTX_PATHS_POLDER_GAME_RUNONREADYRESTART=yes
      - MTX_PATHS_POLDER_GAME_WEBRTC_SOURCE=publisher

volumes:
  caddy_data:
  caddy_config:
